### ISSUE TITLE
Cursos randomly moving on some git branches

### ISSUE THREAD

**Issue by benmezger** [mgee/slimline#21]
For some reason, the cursor moves one space behind when entering some `git` repositories, which after some time it makes the line unusable

See: https://asciinema.org/a/zrMQ55rA3hM16xbue6DdlA3Ym

Any thoughts on how to fix this?

**Comment by mengelbrecht** [comment]
I think this is caused by the `⚡` unicode symbol in the git output when the current branch has no tracked upstream branch.

Are you using iTerm? If so can you check if the setting *Preferences > Profiles > Text > Use Unicode version 9 widths* is enabled? (Similar issue here: https://gitlab.com/gnachman/iterm2/issues/7162)
Also if you are using tmux try it without tmux and see if the issue still persists.

As a workaround you can try the following setting before loading slimline which will replace the  `⚡` symbol with `!`:
```shell
export GITLINE_NO_TRACKED_UPSTREAM='upstream ${red}!${reset}'
```

**Comment by benmezger** [comment]
@mengelbrecht thanks for the quick reply and for the software.

I am not using iTerm2, although I tried doing what you mentioned (both enabling/disabling) it did not work out for me (I remember though I had the same issue with your fish version, and enabling version 9 worked, see [1]).

In Alacritty (Terminal emulator I use), also no luck, however, tracking the upstream branch solved the issue. 

Thanks again!

[1] - https://github.com/fish-shell/fish-shell/issues/5564
