### ISSUE TITLE
gitline.py enhancments.

### ISSUE THREAD

**Issue by ghost** [mgee/slimline#7]
Hey,

would you consider adding merge, rebase, cherry-picking and bisect state information to gitline.py?

Example implementation can be found [here](http://repo.or.cz/w/git.git/blob/1e6f5b22ad318446500fbd3b94b733eddd5b6414:/contrib/completion/git-prompt.sh#l377).

Thanks.

**Comment by mengelbrecht** [comment]
Hi, this is a good idea. I will look into it.

**Comment by mengelbrecht** [comment]
@kwinczek you can test the [next branch](/mgee/slimline/tree/next) which includes numerous improvements to gitline.

The new gitline version detects if a tag is checked out and what state the repository currently is in.
However since a lot of the internals have changed and gitline is its own small project now, the settings for gitline have changed from `SLIMLINE_GIT_*` to `GITLINE_*`.

**Comment by ghost** [comment]
Yeah, seems OK to me. Run a very quick check only though. Thanks!

**Comment by mengelbrecht** [comment]
Fixed by 36089a2.

@kwinczek the next branch was merged to master and is now gone.
